services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - 81:80

  php:
    image: php:fpm
    working_dir: /usr/src/myphp
    volumes:
      - ./php:/usr/src/myphp
